# Generated by Django 2.2.7 on 2020-01-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20200116_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date2',
            new_name='date',
        ),
    ]
