# Generated by Django 2.2.7 on 2020-01-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200116_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date2',
        ),
    ]
