# Generated by Django 2.2.7 on 2020-01-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_auto_20200116_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date2',
            new_name='date',
        ),
    ]
